- name: Deploy via SSH
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.HOST }}
      username: root
      key: ${{ secrets.SSH_KEY }}
      script: |
        cd /var/www/codefolio
        if [ ! -d ".git" ]; then
          git clone https://github.com/NedimHodzic04/codefolio.git .
        else
          git pull origin main
        fi
        npm install
        pm2 restart all || pm2 start server.js --name "codefolio-api"